export const projects = [
  { 
    "id":340957,
    "completed_at":"2018-10-13T20:04:49.286Z",
    "icon": "fa-map-marked-alt",
    "iconColor": "purple",
    "description":"Build a single page map application using React and the Google Maps API. Integrate a third-party data API and make your app accessible and usable offline.",
    "archive_url":"https://review-api.udacity.com/api/v1/submissions/1506252/archive",
    "github_url":"https://github.com/rob9095/fend-maps-app",
    "hosted_url":"http://surfcast-rt.herokuapp.com/",
    "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-8dfb4f72a2c972d15cd7da202a14baab.png",
    "name":"Surfcast - Maps App",
    "nanodegree_name":"Front End Web Developer II Nanodegree",
    "skills":[  

    ],
    "position":1,
    "type":"UDACITY",
    "udacity_key":"11085313332"
  },
  {  
    "id":250221,
    "icon": "fa-brain",
    "iconColor": "teal",
    "completed_at":"2018-05-03T05:37:18.781Z",
    "description":"Built a complete browser-based card matching game (also known as Concentration). But this isn’t just any memory game! It’s a shnazzy, well-designed, feature-packed memory game!",
    "archive_url":"https://review-api.udacity.com/api/v1/submissions/1193405/archive",
    "github_url":"https://github.com/rob9095/memory-card-game",
    "hosted_url":"https://codepen.io/rob9095/pen/odZyyP",
    "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-838391c13e1318be9326f7d83b266218.png",
    "name":"Memory Game",
    "nanodegree_name":"Front-End",
    "skills":[  

    ],
    "position":2,
    "type":"UDACITY",
    "udacity_key":"11085313332"
  },
  {  
     "id":262074,
     "icon": "fa-gamepad",
     "iconColor": "pink",
     "completed_at":"2018-05-29T11:16:40.074Z",
     "description":"An HTML5 Canvas powered video game, developed using the best practices in Object Oriented JavaScript.",
     "archive_url":"https://review-api.udacity.com/api/v1/submissions/1247403/archive",
     "github_url":"https://github.com/rob9095/arcade-game",
     "hosted_url":"https://frogger-clone-rt.herokuapp.com/",
     "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-ebaaa524873c66bb4a1407f054c70a46.png",
     "name":"Classic Arcade Game Clone",
     "nanodegree_name":"Front-End",
     "skills":['HTML5 Canvas','Object-Oriented Programming','JavaScript'],
     "position":3,
     "type":"UDACITY",
     "udacity_key":"11085313332"
  },
  {  
     "id":340956,
     "icon": "fa-book-reader",
     "iconColor": "purple",
     "completed_at":"2018-09-29T08:03:21.986Z",
     "description":"Built a responsive web application that allows users to select and categorize books into a virtual bookshelf. Leveraged React to support a dynamic user interface that interacts with an API server and client library.",
     "archive_url":"https://review-api.udacity.com/api/v1/submissions/1480991/archive",
     "github_url":"https://github.com/rob9095/fend-my-reads-app",
     "hosted_url":null,
     "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-9a46a293e78284df5c34bd014b587ca3.png",
     "name":"MyReads: A Book Lending App",
     "nanodegree_name":"React",
     "skills":[ 'JavaScript','React','Babel','HTML5','Fetch API','CSS3','Webpack'],
     "position":4,
     "type":"UDACITY",
     "udacity_key":"11085313332"
  },
  {  
     "id":340958,
     "icon": "fa-utensils",
     "iconColor": "teal",
     "completed_at":"2018-09-04T03:31:56.705Z",
     "description":"In this real world case study, given the front end code for a static Restaurant Reviews App, revise the site to be responsive and achieve accessibility standards.",
     "archive_url":"https://review-api.udacity.com/api/v1/submissions/1437658/archive",
     "github_url":"https://github.com/rob9095/fend-restaurant-app",
     "hosted_url":null,
     "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-9fa30f158726033a240d955798a77d28.png",
     "name":"Restaurant Reviews App",
     "nanodegree_name":"Front End Web Developer II Nanodegree",
     "skills":['JavaScript','HTML5','CSS3'],
     "position":5,
     "type":"UDACITY",
     "udacity_key":"11085313332"
  },
  {  
     "id":342546,
     "icon": "fa-pencil-alt",
     "iconColor": "pink",
     "completed_at":null,
     "description":"Single-page web app that allows users to draw pixel art on a customizable canvas.",
     "archive_url":null,
     "github_url":"https://github.com/rob9095/pixel-drawing-js",
     "hosted_url":"https://codepen.io/rob9095/full/ppOWpG/",
     "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-94ca8db87c04b8f0d8df8e19bca794fc.png",
     "name":"Pixel Drawing App",
     "nanodegree_name":null,
     "skills":['JavaScript'],
     "position":6,
     "type":"PERSONAL",
     "udacity_key":"11085313332"
  },
  {  
    "id":340959,
    "icon": "fa-rss",
    "iconColor": "purple",
    "completed_at":"2018-07-15T09:39:13.439Z",
    "description":"Wrote comprehensive unit tests, using the Jasmine testing framework, for an RSS Feed Reader application that uses Google's RSS API.",
    "archive_url":"https://review-api.udacity.com/api/v1/submissions/1340509/archive",
    "github_url":null,
    "hosted_url":null,
    "image_url":"https://s3-us-west-2.amazonaws.com/udacity-profiles/production/projects/11085313332-project-0113e5018097ac08fc942ea6030b5393.png",
    "name":"Feed Reader Testing",
    "nanodegree_name":"Front-End",
    "skills":['Jasmine','JavaScript'],
    "position":7,
    "type":"UDACITY",
    "udacity_key":"11085313332"
 },
]